import { describe, it, expect } from 'vitest';
import { checkFile } from './check-file';

// We only assert on PAGE_TRANSITION_* codes; unrelated violations are ignored.
const ptCodes = (code: string) =>
  checkFile(code, { kind: 'page' }).filter((v) => v.code.startsWith('PAGE_TRANSITION_')).map((v) => v.code);

const PAGE = (body: string) => `'use client';
import React from 'react';
export default function Page() {
  ${body}
  return <div data-id="root"></div>;
}`;

describe('oracle: Page Transitions (View Transitions) dialect', () => {
  it('bounces the MPA @view-transition opt-in', () => {
    const css = PAGE(`const x = 1;`).replace('return', `void '@view-transition { navigation: auto; }';\n  return`);
    expect(ptCodes(css)).toContain('PAGE_TRANSITION_MPA_FORBIDDEN');
  });

  it('bounces hand-written ::view-transition keyframes', () => {
    const code = PAGE(`const css = '::view-transition-old(root) { animation: 0.4s ease both x; }';`);
    expect(ptCodes(code)).toContain('PAGE_TRANSITION_RAW_VT_CSS');
  });

  it('exempts the generated runtime helper (it legitimately emits VT CSS)', () => {
    const runtime = `// @generated by Revyme — Page Effects runtime helpers. Do not edit.\n`
      + `export function build() { return '::view-transition-new(root) { animation: none; }'; }`;
    expect(ptCodes(runtime)).not.toContain('PAGE_TRANSITION_RAW_VT_CSS');
  });

  it('warns on an UNGUARDED document.startViewTransition call', () => {
    const code = PAGE(`function go(){ document.startViewTransition(() => {}); }`);
    expect(ptCodes(code)).toContain('PAGE_TRANSITION_NEEDS_GUARD');
  });

  it('a GUARDED startViewTransition does not warn', () => {
    const code = PAGE(`function go(){ if (!document.startViewTransition) return; document.startViewTransition(() => {}); }`);
    expect(ptCodes(code)).not.toContain('PAGE_TRANSITION_NEEDS_GUARD');
  });

  it('a plain page with no view-transition usage is clean', () => {
    expect(ptCodes(PAGE(`const x = 1;`))).toEqual([]);
  });
});
