import { describe, it, expect } from 'vitest';
import { transform } from '@babel/standalone';
import {
  parsePageEffects,
  serializePageEffects,
  createDefaultSide,
  isEmptyPageEffects,
  upsertEffectInMap,
  removeEffectFromMap,
  listEffectsForPage,
  type PageEffect,
  type PageEffectsMap,
} from './page-effects-config';

const parses = (code: string) =>
  expect(() => transform(code, { presets: ['typescript'], filename: 'f.ts' })).not.toThrow();

const sampleMap = (): PageEffectsMap => ({
  __default: { preset: 'crossfade', target: 'all', exit: createDefaultSide(), enter: { ...createDefaultSide(), opacity: 0 } },
  pages: {
    '/team': {
      all: { preset: 'fade-out-in', target: 'all', exit: createDefaultSide() },
      byTarget: { '/': { preset: 'slide-right', target: '/', enter: { ...createDefaultSide(), offsetX: -100 } } },
    },
  },
});

describe('page-effects-config: serialize/parse', () => {
  it('round-trips a map through the generated module', () => {
    const map = sampleMap();
    const code = serializePageEffects(map);
    expect(code).toContain('export const PAGE_EFFECTS =');
    expect(code).toContain('as const;');
    expect(code).toContain('@generated by Revyme');
    parses(code);
    expect(parsePageEffects(code)).toEqual(map);
  });

  it('parse tolerates surrounding module content (imports, comments)', () => {
    const code = `// header\nimport x from 'y';\nexport const PAGE_EFFECTS = ${JSON.stringify(sampleMap())} as const;\nconsole.log('after');`;
    expect(parsePageEffects(code)).toEqual(sampleMap());
  });

  it('absent / malformed → empty map', () => {
    expect(parsePageEffects('')).toEqual({ pages: {} });
    expect(parsePageEffects('export const OTHER = {};')).toEqual({ pages: {} });
    expect(parsePageEffects('export const PAGE_EFFECTS = { not json,, } as const;')).toEqual({ pages: {} });
  });

  it('parse guarantees a pages object even if omitted', () => {
    const code = `export const PAGE_EFFECTS = {"__default":{"preset":"crossfade","target":"all"}} as const;`;
    const out = parsePageEffects(code);
    expect(out.pages).toEqual({});
    expect(out.__default?.preset).toBe('crossfade');
  });
});

describe('page-effects-config: map mutators', () => {
  const eff = (target: string, preset = 'crossfade'): PageEffect => ({ preset, target });

  it("upsert 'all' on Home → __default (site-wide)", () => {
    const m = upsertEffectInMap({ pages: {} }, '/', eff('all'));
    expect(m.__default?.preset).toBe('crossfade');
    expect(m.pages['/']).toBeUndefined();
  });
  it("upsert 'all' on a non-home page → that page's `all`", () => {
    const m = upsertEffectInMap({ pages: {} }, '/team', eff('all'));
    expect(m.pages['/team'].all?.preset).toBe('crossfade');
    expect(m.__default).toBeUndefined();
  });
  it('upsert a specific target → byTarget', () => {
    const m = upsertEffectInMap({ pages: {} }, '/team', eff('/'));
    expect(m.pages['/team'].byTarget['/'].preset).toBe('crossfade');
  });
  it('upsert is immutable (does not mutate the input map)', () => {
    const base: PageEffectsMap = { pages: {} };
    upsertEffectInMap(base, '/team', eff('/'));
    expect(base.pages['/team']).toBeUndefined();
  });
  it('remove drops the entry + prunes empty buckets', () => {
    let m = upsertEffectInMap({ pages: {} }, '/team', eff('/'));
    m = removeEffectFromMap(m, '/team', '/');
    expect(m.pages['/team']).toBeUndefined();
  });
  it("remove 'all' on Home drops __default", () => {
    let m = upsertEffectInMap({ pages: {} }, '/', eff('all'));
    m = removeEffectFromMap(m, '/', 'all');
    expect(m.__default).toBeUndefined();
  });
  it('listEffectsForPage returns home __default + page all + byTarget', () => {
    let m = upsertEffectInMap({ pages: {} }, '/', eff('all', 'site'));
    expect(listEffectsForPage(m, '/').map((e) => e.preset)).toEqual(['site']);
    m = upsertEffectInMap({ pages: {} }, '/team', eff('all', 'team-all'));
    m = upsertEffectInMap(m, '/team', eff('/', 'team-home'));
    expect(listEffectsForPage(m, '/team').map((e) => e.preset).sort()).toEqual(['team-all', 'team-home']);
  });
});

describe('page-effects-config: isEmptyPageEffects', () => {
  it('empty map → true', () => {
    expect(isEmptyPageEffects({ pages: {} })).toBe(true);
    expect(isEmptyPageEffects({ pages: { '/a': { byTarget: {} } } })).toBe(true);
  });
  it('any default / all / byTarget → false', () => {
    expect(isEmptyPageEffects({ __default: { preset: 'crossfade', target: 'all' }, pages: {} })).toBe(false);
    expect(isEmptyPageEffects({ pages: { '/a': { all: { preset: 'x', target: 'all' }, byTarget: {} } } })).toBe(false);
    expect(isEmptyPageEffects({ pages: { '/a': { byTarget: { '/b': { preset: 'x', target: '/b' } } } } })).toBe(false);
  });
});
