// providers-gen.ts — generates app/providers.tsx from the i18n config.
//
// The provider is a GENERATED file (like app/page.tsx server wrappers): its
// messages imports must match the configured locales (the old static template
// hardcoded en/fr/es — an added Italian locale silently never loaded its
// dictionary on the live site), and since the locale-routes feature the
// active locale is ROUTE-FIRST: a `/fr/...` URL wins over the stored client
// preference, so `/fr` server-renders French HTML (the SEO path). The
// `locale-change` event + localStorage remain the client channel used by the
// canvas preview and by unprefixed URLs.
//
// Regenerated by ensureIntlScaffold whenever the expected source drifts
// (locale added/removed). Hand-written providers (no generation markers) are
// left alone.

import type { I18nConfig } from '@/shared/types';

/** Version marker — bump when the template shape changes so older generated
 *  providers are upgraded on load. */
export const PROVIDERS_MARKER = '@revyme-providers v2';

/** A locale code safe to interpolate into generated code/identifiers. */
function safeLocale(code: string): boolean {
  return /^[a-z]{2,3}(-[A-Za-z0-9]+)?$/.test(code);
}

function importIdent(code: string): string {
  return code.replace(/-/g, '_') + 'Messages';
}

export function buildProvidersSource(config: I18nConfig): string {
  const locales = config.locales.map((l) => l.code).filter(safeLocale);
  const codes = locales.length > 0 ? locales : ['en'];
  const defaultLocale = safeLocale(config.defaultLocale) ? config.defaultLocale : 'en';
  const imports = codes
    .map((c) => `import ${importIdent(c)} from '@/messages/${c}.json';`)
    .join('\n');
  const mapEntries = codes.map((c) => `  '${c}': ${importIdent(c)},`).join('\n');

  return `'use client';

/** ${PROVIDERS_MARKER} — GENERATED from i18n/config.json (locales: ${codes.join(', ')}).
 *  The editor regenerates this file when locales change. Do not hand-edit. */

import { useEffect, useState } from 'react';
import { usePathname } from 'next/navigation';
import { ThemeProvider } from 'next-themes';
import { NextIntlClientProvider } from 'next-intl';

${imports}

const messagesByLocale: Record<string, any> = {
${mapEntries}
};
const DEFAULT_LOCALE = '${defaultLocale}';
const LOCALES = Object.keys(messagesByLocale);

/** '/fr/about' -> 'fr' when fr is a configured non-default locale, else null. */
function localeFromPath(pathname: string | null): string | null {
  const seg = (pathname || '/').split('/')[1];
  return seg && seg !== DEFAULT_LOCALE && LOCALES.includes(seg) ? seg : null;
}

export function Providers({ children }: { children: React.ReactNode }) {
  // ROUTE-FIRST locale: /fr/... serves French on the server render itself
  // (usePathname resolves during SSR), so crawlers get translated HTML.
  const routeLocale = localeFromPath(usePathname());
  const [clientLocale, setClientLocale] = useState(DEFAULT_LOCALE);
  const locale = routeLocale ?? clientLocale;

  // Client channel: persisted preference + the 'locale-change' event any
  // component (LocaleSwitcher) can dispatch. Only applies on unprefixed URLs.
  useEffect(() => {
    if (typeof window === 'undefined') return;
    try {
      const stored = window.localStorage.getItem('locale');
      if (stored && messagesByLocale[stored]) setClientLocale(stored);
    } catch { /* private mode — ignore */ }

    const handler = (e: Event) => {
      const detail = (e as CustomEvent).detail;
      const next = detail?.locale;
      if (typeof next === 'string' && messagesByLocale[next]) setClientLocale(next);
    };
    window.addEventListener('locale-change', handler);
    return () => window.removeEventListener('locale-change', handler);
  }, []);

  // Mirror the ACTIVE locale to <html lang> (+ dir for RTL scripts) and
  // persist it, so :lang() CSS fires and the choice survives navigation to
  // unprefixed URLs.
  useEffect(() => {
    if (typeof document !== 'undefined') {
      if (document.documentElement.lang !== locale) document.documentElement.lang = locale;
      const rtl = ['ar', 'he', 'fa', 'ur', 'ps', 'sd', 'ku', 'dv', 'yi'].includes(locale.split('-')[0]);
      if (rtl) document.documentElement.dir = 'rtl';
      else document.documentElement.removeAttribute('dir');
    }
    try { window.localStorage.setItem('locale', locale); } catch { /* ignore */ }
  }, [locale]);

  const messages = messagesByLocale[locale] || messagesByLocale[DEFAULT_LOCALE];

  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
        {/* lang on a wrapper (display:contents = no box) so :lang() styles
            match in the SERVER-rendered HTML too — <html lang> is only
            patched client-side. */}
        <div lang={locale} style={{ display: 'contents' }}>
          {children}
        </div>
      </ThemeProvider>
    </NextIntlClientProvider>
  );
}
`;
}

/** Does this providers.tsx look editor-GENERATED (any version)? Generated
 *  files are safe to regenerate; a hand-written provider is left alone. */
export function looksGeneratedProviders(code: string): boolean {
  return code.includes(PROVIDERS_MARKER)
    || (code.includes('messagesByLocale') && code.includes("'locale-change'"));
}
