/**
 * form-gen.ts — wires a `<form>` so it actually submits.
 *
 * When a form is created (dropped on the canvas), we attach an inline
 * `onSubmit` handler that POSTs the form's fields to the same-origin
 * `/api/form` route. On a published site that route is the relay injected at
 * deploy (build-project.ts), which forwards to the Revyme Forms Worker; the
 * worker looks up the form's config (recipient/webhook) by `formId`, sends the
 * email + stores the submission, and returns `{ ok, redirect }`.
 *
 * Source = deploy reality: the handler is real code in the page source, not a
 * deploy-time transform. In the CANVAS the Renderer builds elements from the
 * parsed node model (which doesn't carry `onSubmit`), so the handler never
 * fires in the editor — only on the published site.
 *
 * The POST body is `{ formId, fields, _hp }`:
 *   - `formId`  — the form's `data-id` (selects which config the worker uses).
 *   - `fields`  — every named input, via `FormData` → object.
 *   - `_hp`     — honeypot value (null when no honeypot input is present; the
 *                 worker treats a truthy `_hp` as a bot and silently drops it).
 */

import { trace } from '@/shared/debug-trace';
import { projectFS } from '../project/project-fs';
import { findJSXDataIdIndex, findTagClose } from './generator-utils';

/** The endpoint the published form posts to (same-origin relay → Forms Worker). */
export const FORM_SUBMIT_ENDPOINT = '/api/form';

/** Path of the same-origin relay route handler in the project FS. A real
 *  Next.js App Router route so it ships with BOTH publish and export. */
export const FORM_ROUTE_PATH = 'app/api/form/route.ts';

/**
 * The relay route handler. A thin CF→CF proxy: it forwards the submission to
 * the Revyme Forms Worker, adding the site's own id + token (server-only env
 * bindings injected at deploy). Contains NO secret values — only `env.X`
 * references — and is a server file (never bundled to the browser), so it's
 * safe to keep in the project FS / an exported repo.
 */
export const FORM_ROUTE_CONTENT = `// AUTO-GENERATED by Revyme — same-origin relay to the Forms Worker. Do not edit.
import { env } from "cloudflare:workers";

export async function POST(req) {
  let body;
  try {
    body = await req.json();
  } catch {
    return Response.json({ ok: false, error: "Invalid request" }, { status: 400 });
  }
  const formsUrl = env.REVYME_FORMS_URL;
  if (!formsUrl) {
    return Response.json({ ok: false, error: "Forms not configured" }, { status: 503 });
  }
  try {
    const headers = { "Content-Type": "application/json" };
    if (env.REVYME_FORM_TOKEN) headers["Authorization"] = "Bearer " + env.REVYME_FORM_TOKEN;
    const res = await fetch(formsUrl, {
      method: "POST",
      headers,
      body: JSON.stringify({
        websiteId: env.REVYME_WEBSITE_ID,
        formId: body && body.formId,
        fields: (body && body.fields) || {},
        _hp: body && body._hp,
      }),
    });
    const data = await res.json().catch(() => ({ ok: res.ok }));
    return Response.json(data, { status: res.status });
  } catch (e) {
    return Response.json({ ok: false, error: "Upstream error" }, { status: 502 });
  }
}
`;

/**
 * Ensure the relay route exists in the project FS. Idempotent + side-effecting
 * (call from the mutation handler, like ensureLoadMoreComponentFile). Created
 * the first time a form is added so it ships with publish AND export.
 */
export function ensureFormRouteFile(): void {
  if (projectFS.readFile(FORM_ROUTE_PATH) != null) return;
  projectFS.writeFile(FORM_ROUTE_PATH, FORM_ROUTE_CONTENT);
  trace.action('form-gen:ensureFormRouteFile', { path: FORM_ROUTE_PATH });
}

/**
 * Build the inline `onSubmit` handler for a form with the given id.
 *
 * When `stateSetter` is supplied (the `setFormState<Id>` paired with the form's
 * lifecycle var) the handler drives that var through the form lifecycle —
 * `'loading'` up-front, `'success'`/`'error'` on the response, then back to
 * `'idle'` after a short delay — so any instance inside the form whose
 * `initialVariant` is mapped to a state (via the Form State tool) switches to
 * the matching variant. See `form-state-gen.ts` / `form-submit-gen.ts`.
 */
export function buildFormSubmitHandler(formId: string, stateSetter?: string): string {
  // Compact, double-quoted (no backticks) so it round-trips through the JSX
  // parser/generator cleanly. `e.currentTarget` is the form element.
  const settle = (state: string) =>
    stateSetter ? `${stateSetter}("${state}"); setTimeout(() => ${stateSetter}("idle"), 4000);` : '';
  return (
    `onSubmit={async (e) => {\n` +
    `        e.preventDefault();\n` +
    (stateSetter ? `        ${stateSetter}("loading");\n` : '') +
    `        const formEl = e.currentTarget;\n` +
    `        const fd = new FormData(formEl);\n` +
    `        const _hp = fd.get("_hp");\n` +
    `        fd.delete("_hp");\n` +
    `        const fields = Object.fromEntries(fd.entries());\n` +
    `        try {\n` +
    `          const res = await fetch("${FORM_SUBMIT_ENDPOINT}", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ formId: ${JSON.stringify(
      formId,
    )}, fields, _hp }) });\n` +
    `          const data = await res.json().catch(() => ({}));\n` +
    `          if (data && data.redirect) { window.location.href = data.redirect; return; }\n` +
    `          if (res.ok && (!data || data.ok !== false)) { formEl.reset();${stateSetter ? ` ${settle('success')}` : ''} }` +
    (stateSetter ? ` else { ${settle('error')} }` : '') +
    `\n        } catch (err) {${stateSetter ? ` ${settle('error')}` : ''}}\n` +
    `      }}`
  );
}

/** True when the form with `formId` already carries an `onSubmit` handler. */
export function hasFormSubmitHandler(code: string, formId: string): boolean {
  const idIdx = findJSXDataIdIndex(code, formId);
  if (idIdx < 0) return false;
  const ltIdx = code.lastIndexOf('<', idIdx);
  if (ltIdx < 0) return false;
  const tagClose = findTagClose(code, idIdx);
  if (tagClose < 0) return false;
  return /\bonSubmit\s*=/.test(code.slice(ltIdx, tagClose));
}

/**
 * Attach the submit handler to the `<form>` (or `<motion.form>`) with `formId`.
 * Idempotent (no-op if it already has an `onSubmit`). Returns the code
 * unchanged when the node isn't a form or can't be located.
 *
 * `stateSetter` (optional) wires the lifecycle toggle into the handler — pass
 * the `setFormState<Id>` paired with the form's `formState<Id>` var.
 */
export function wireFormSubmitInCode(code: string, formId: string, stateSetter?: string): string {
  const idIdx = findJSXDataIdIndex(code, formId);
  if (idIdx < 0) {
    trace.action('form-gen:wire-skip', { formId, reason: 'data-id-not-found' });
    return code;
  }
  const ltIdx = code.lastIndexOf('<', idIdx);
  if (ltIdx < 0) return code;
  // Confirm the enclosing tag is a form (the only tag we wire).
  const tagName = code.slice(ltIdx + 1, idIdx).trim().split(/[\s/>]/)[0];
  if (tagName !== 'form' && tagName !== 'motion.form') {
    trace.action('form-gen:wire-skip', { formId, reason: 'not-a-form', tagName });
    return code;
  }
  if (hasFormSubmitHandler(code, formId)) {
    trace.action('form-gen:wire-skip', { formId, reason: 'already-wired' });
    return code;
  }
  // Insert the handler just before `data-id` (inside the opening tag).
  const handler = buildFormSubmitHandler(formId, stateSetter) + ' ';
  const next = code.slice(0, idIdx) + handler + code.slice(idIdx);
  trace.action('form-gen:wired', { formId, tagName });
  return next;
}
