/**
 * page-transitions-gen.ts — generates the Page Effects RUNTIME into user source.
 *
 * Three files are scaffolded next to the route group's LayoutClient (so they
 * deploy as ordinary source — no backend change, source = deploy reality):
 *   - page-effects.ts          → the PAGE_EFFECTS data map (editor writes this)
 *   - page-effects-runtime.ts  → standalone pure helpers (resolve + CSS build),
 *                                a hand-mirrored copy of view-transition-css.ts
 *                                (a parity test guards against drift)
 *   - page-transitions.tsx     → the <PageTransitions> client controller
 * and `<PageTransitions>` is injected around `{children}` in the LayoutClient.
 *
 * ONE mechanism for preview + deploy: both are Next App Router SPA, so
 * document.startViewTransition() wrapping the route change (resolved on
 * usePathname change) works in both.
 */

import { trace } from '@/shared/debug-trace';
import { projectFS } from '../project/project-fs';
import { serializePageEffects } from '../project/page-effects-config';

/** The deployed pure helpers. Plain JS (no TS types / editor imports) so it's
 *  self-contained user source AND directly eval-able by the parity test. Mirrors
 *  src/code/generation/view-transition-css.ts. */
export const PAGE_EFFECTS_RUNTIME_SOURCE = `// @generated by Revyme — Page Effects runtime helpers. Do not edit. @rt-v2
var DEFAULT_BEZIER = [0.42, 0, 0.58, 1];

export function sideToTransform(s) {
  var parts = [];
  if (s.offsetX !== 0 || s.offsetY !== 0) {
    var ux = s.offsetXUnit === 'relative' ? '%' : 'px';
    var uy = s.offsetYUnit === 'relative' ? '%' : 'px';
    parts.push('translate(' + s.offsetX + ux + ', ' + s.offsetY + uy + ')');
  }
  if (s.scale !== 1) parts.push('scale(' + s.scale + ')');
  if (s.rotate === '3d') {
    if (s.rotateX !== 0 || s.rotateY !== 0 || s.rotateZ !== 0) {
      parts.push('perspective(1200px) rotateX(' + s.rotateX + 'deg) rotateY(' + s.rotateY + 'deg) rotateZ(' + s.rotateZ + 'deg)');
    }
  } else if (s.rotateZ !== 0) {
    parts.push('rotate(' + s.rotateZ + 'deg)');
  }
  return parts.length ? parts.join(' ') : 'none';
}

export function maskToClip(mask, phase) {
  if (mask.type === 'circle') {
    var ox = mask.originX + (mask.originXUnit === 'rel' ? '%' : 'px');
    var oy = mask.originY + (mask.originYUnit === 'rel' ? '%' : 'px');
    return phase === 'full' ? 'circle(150% at ' + ox + ' ' + oy + ')' : 'circle(0% at ' + ox + ' ' + oy + ')';
  }
  if (phase === 'full') return 'inset(0 0 0 0)';
  if (mask.type === 'wipe-left') return 'inset(0 0 0 100%)';
  if (mask.type === 'wipe-right') return 'inset(0 100% 0 0)';
  if (mask.type === 'wipe-up') return 'inset(100% 0 0 0)';
  if (mask.type === 'wipe-down') return 'inset(0 0 100% 0)';
  return 'inset(0 0 0 0)';
}

export function springToLinearEasing(spring) {
  var k = spring.stiffness != null ? spring.stiffness : 100;
  var c = spring.damping != null ? spring.damping : 10;
  var m = spring.mass != null ? spring.mass : 1;
  var w0 = Math.sqrt(k / m);
  var zeta = c / (2 * Math.sqrt(k * m));
  var settle = zeta > 0 ? Math.min(Math.max(-Math.log(0.01) / (zeta * w0), 0.2), 4) : 1;
  var STEPS = 24;
  var stops = [];
  for (var i = 0; i <= STEPS; i++) {
    var t = (i / STEPS) * settle;
    var x;
    if (zeta < 1) {
      var wd = w0 * Math.sqrt(1 - zeta * zeta);
      x = 1 - Math.exp(-zeta * w0 * t) * (Math.cos(wd * t) + ((zeta * w0) / wd) * Math.sin(wd * t));
    } else if (zeta === 1) {
      x = 1 - Math.exp(-w0 * t) * (1 + w0 * t);
    } else {
      var sq = Math.sqrt(zeta * zeta - 1);
      var r1 = -w0 * (zeta - sq);
      var r2 = -w0 * (zeta + sq);
      var A = r2 / (r2 - r1);
      var B = -r1 / (r2 - r1);
      x = 1 - (A * Math.exp(r1 * t) + B * Math.exp(r2 * t));
    }
    stops.push(Math.round(x * 1000) / 1000);
  }
  stops[0] = 0;
  stops[stops.length - 1] = 1;
  return { easing: 'linear(' + stops.join(', ') + ')', duration: Math.round(settle * 1000) / 1000 };
}

export function resolveTiming(t) {
  if (t.kind === 'spring') {
    var s = springToLinearEasing(t);
    return { easing: s.easing, duration: s.duration, delay: t.delay || 0 };
  }
  var b = t.bezier || DEFAULT_BEZIER;
  return { easing: 'cubic-bezier(' + b[0] + ', ' + b[1] + ', ' + b[2] + ', ' + b[3] + ')', duration: t.duration != null ? t.duration : 0.4, delay: t.delay || 0 };
}

export function buildViewTransitionCSS(exit, enter) {
  var lines = [];
  lines.push('@media (prefers-reduced-motion: reduce) {');
  lines.push('  ::view-transition-old(root), ::view-transition-new(root), ::view-transition-group(root) { animation-duration: 0s !important; animation-delay: 0s !important; }');
  lines.push('}');
  // Per-effect blend (mirrors view-transition-css.ts): a pure opacity crossfade
  // needs plus-lighter + isolate so the two half-faded snapshots sum to full
  // coverage — \`normal\` reveals the <html> backdrop (white by default, since the
  // page bg is on a child div) = white flash. Slide/push/wipe keep \`normal\`.
  var anyTransform =
    (!!exit && (sideToTransform(exit) !== 'none' || !!exit.mask)) ||
    (!!enter && (sideToTransform(enter) !== 'none' || !!enter.mask));
  if (anyTransform) {
    lines.push('::view-transition-image-pair(root) { isolation: auto; }');
    lines.push('::view-transition-old(root), ::view-transition-new(root) { mix-blend-mode: normal; }');
  } else {
    lines.push('::view-transition-image-pair(root) { isolation: isolate; }');
    lines.push('::view-transition-old(root), ::view-transition-new(root) { mix-blend-mode: plus-lighter; }');
  }
  if (exit) {
    var te = resolveTiming(exit.transition);
    lines.push('::view-transition-old(root) { animation: ' + te.duration + 's ' + te.easing + ' ' + te.delay + 's both revyme-vt-exit; transform-origin: 50% 50%; }');
    var ef = exit.mask ? maskToClip(exit.mask, 'full') : null;
    var et = exit.mask ? maskToClip(exit.mask, 'clipped') : null;
    lines.push('@keyframes revyme-vt-exit {');
    lines.push('  from { opacity: 1; transform: none;' + (ef ? ' clip-path: ' + ef + ';' : '') + ' }');
    lines.push('  to { opacity: ' + exit.opacity + '; transform: ' + sideToTransform(exit) + ';' + (et ? ' clip-path: ' + et + ';' : '') + ' }');
    lines.push('}');
  } else {
    lines.push('::view-transition-old(root) { animation: none; }');
  }
  if (enter) {
    var tn = resolveTiming(enter.transition);
    lines.push('::view-transition-new(root) { animation: ' + tn.duration + 's ' + tn.easing + ' ' + tn.delay + 's both revyme-vt-enter; transform-origin: 50% 50%; }');
    var nf = enter.mask ? maskToClip(enter.mask, 'clipped') : null;
    var nt = enter.mask ? maskToClip(enter.mask, 'full') : null;
    lines.push('@keyframes revyme-vt-enter {');
    lines.push('  from { opacity: ' + enter.opacity + '; transform: ' + sideToTransform(enter) + ';' + (nf ? ' clip-path: ' + nf + ';' : '') + ' }');
    lines.push('  to { opacity: 1; transform: none;' + (nt ? ' clip-path: ' + nt + ';' : '') + ' }');
    lines.push('}');
  } else {
    lines.push('::view-transition-new(root) { animation: none; }');
  }
  return lines.join('\\n');
}

export function resolvePageEffect(map, source, dest) {
  var bucket = map && map.pages ? map.pages[source] : null;
  if (bucket && bucket.byTarget && bucket.byTarget[dest]) return bucket.byTarget[dest];
  if (bucket && bucket.all) return bucket.all;
  if (map && map.__default) return map.__default;
  return null;
}
`;

/** The <PageTransitions> client controller (plan §4.1). Capture-phase click
 *  interception wraps the route change in document.startViewTransition. */
export const PAGE_TRANSITIONS_SOURCE = `'use client';
// @generated by Revyme — Page Effects controller. Do not edit.
import * as React from 'react';
import { usePathname, useRouter } from 'next/navigation';
import { PAGE_EFFECTS } from './page-effects';
import { resolvePageEffect, buildViewTransitionCSS } from './page-effects-runtime';

export function PageTransitions({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const router = useRouter();
  const finishRef = React.useRef<null | (() => void)>(null);

  React.useEffect(() => {
    if (finishRef.current) { finishRef.current(); finishRef.current = null; }
  }, [pathname]);

  React.useEffect(() => {
    if (typeof document === 'undefined' || !(document as any).startViewTransition) return;
    function onClick(e: MouseEvent) {
      const a = (e.target as Element)?.closest?.('a[href]') as HTMLAnchorElement | null;
      if (!a) return;
      if (e.defaultPrevented) return;
      if (e.metaKey || e.ctrlKey || e.shiftKey || e.altKey || e.button !== 0) return;
      if (a.target && a.target !== '_self') return;
      if (a.hasAttribute('data-no-vt')) return;
      const href = a.getAttribute('href') || '';
      if (!href || /^https?:\\/\\//.test(href) || href.startsWith('//') ||
          href.startsWith('mailto:') || href.startsWith('tel:') || href.startsWith('#')) return;
      const dest = new URL(href, location.href);
      if (dest.origin !== location.origin) return;
      if (dest.pathname === location.pathname) return;
      const eff = resolvePageEffect(PAGE_EFFECTS as any, location.pathname, dest.pathname);
      if (!eff) return;
      e.preventDefault();
      e.stopImmediatePropagation();
      const styleEl = document.createElement('style');
      styleEl.id = 'revyme-vt-active';
      styleEl.textContent = buildViewTransitionCSS(eff.exit, eff.enter);
      document.head.appendChild(styleEl);
      const vt = (document as any).startViewTransition(() =>
        new Promise<void>((resolve) => {
          finishRef.current = resolve;
          React.startTransition(() => router.push(dest.pathname + dest.search + dest.hash));
        })
      );
      vt.finished.finally(() => styleEl.remove());
    }
    document.addEventListener('click', onClick, true);
    return () => document.removeEventListener('click', onClick, true);
  }, [router]);

  return <>{children}</>;
}
`;

/** The dir holding the LayoutClient (where the 3 runtime files live). */
function dirOf(layoutClientPath: string): string {
  const i = layoutClientPath.lastIndexOf('/');
  return i === -1 ? '' : layoutClientPath.slice(0, i + 1);
}

export function pageEffectsDataPath(layoutClientPath: string): string {
  return dirOf(layoutClientPath) + 'page-effects.ts';
}
function pageEffectsRuntimePath(layoutClientPath: string): string {
  return dirOf(layoutClientPath) + 'page-effects-runtime.ts';
}
export function pageTransitionsPath(layoutClientPath: string): string {
  return dirOf(layoutClientPath) + 'page-transitions.tsx';
}

/** Materialize the 3 runtime files (idempotent; only writes missing ones) +
 *  inject `<PageTransitions>` into the LayoutClient. Side-effecting; call from a
 *  mutation/op, not a pure transform. */
export function ensurePageEffectsScaffold(layoutClientPath: string): void {
  const dataPath = pageEffectsDataPath(layoutClientPath);
  if (projectFS.readFile(dataPath) == null) {
    projectFS.writeFile(dataPath, serializePageEffects({ pages: {} }));
  }
  // Rewrite the runtime when MISSING or OUTDATED. The `@rt-v2` marker bumps
  // whenever the emitted CSS/logic changes (here: the per-effect plus-lighter
  // fix for the crossfade white-flash), so a site scaffolded on an older version
  // self-heals on the next effect edit instead of being stuck on a stale copy
  // (the file is `Do not edit`, so users never touch it — safe to overwrite).
  const runtimePath = pageEffectsRuntimePath(layoutClientPath);
  const existingRuntime = projectFS.readFile(runtimePath);
  if (existingRuntime == null || !existingRuntime.includes('@rt-v2')) {
    projectFS.writeFile(runtimePath, PAGE_EFFECTS_RUNTIME_SOURCE);
  }
  const compPath = pageTransitionsPath(layoutClientPath);
  if (projectFS.readFile(compPath) == null) {
    projectFS.writeFile(compPath, PAGE_TRANSITIONS_SOURCE);
  }
  // NOTE: the LayoutClient `<PageTransitions>` injection is done by the OPS layer
  // via modifyProjectFile (the LayoutClient is an existing file with pending
  // queue state; raw writeFile would lose it).
  trace.action('page-transitions-gen:ensure-scaffold', { layoutClientPath });
}

/** Wrap the LayoutClient's `{children}` in `<PageTransitions>` + add the import.
 *  Idempotent. Pure (exported for testing). */
export function injectPageTransitionsInCode(code: string): string {
  if (code.includes('<PageTransitions>')) return code;
  // Wrap the FIRST top-level `{children}` occurrence.
  const idx = code.indexOf('{children}');
  if (idx === -1) return code;
  let next = code.slice(0, idx) + '<PageTransitions>{children}</PageTransitions>' + code.slice(idx + '{children}'.length);
  // Add the import after the last import (or after 'use client').
  const imp = `import { PageTransitions } from './page-transitions';`;
  if (!next.includes(imp)) {
    const lastImport = next.lastIndexOf('\nimport ');
    if (lastImport !== -1) {
      const eol = next.indexOf('\n', lastImport + 1);
      const at = eol === -1 ? next.length : eol;
      next = next.slice(0, at) + `\n${imp}` + next.slice(at);
    } else {
      // No imports — insert after the 'use client' directive (or at top).
      const uc = next.indexOf("'use client';");
      const at = uc === -1 ? 0 : uc + "'use client';".length;
      next = next.slice(0, at) + `\n${imp}` + next.slice(at);
    }
  }
  trace.action('page-transitions-gen:inject', {});
  return next;
}
